<?xml version="1.0"?>

<!-- This file contains plugins to simulate an Imu sensor attached to the robot. -->
<!-- Documentation can be found at http://wiki.ros.org/hector_gazebo_plugins -->

<robot name="smb" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="IMU" params="base_link simulation">
    <!--                              Imu  Properties 				          	-->
    <xacro:property name="imu_base_link" value="${base_link}"/>
    <xacro:property name="imu_origin_rpy" value="0 0 0"/>
    <xacro:property name="imu_origin_xyz" value="0.2554 -0.02397 ${0.081+chassisHeight/2.0}"/>
    <xacro:property name="imu_update_rate" value="400"/>
    <xacro:property name="imu_link" value="imu_link"/>
    <xacro:property name="imu_topic" value="/imu"/>

    <xacro:if value="${simulation}">
    
    <gazebo>
        <plugin filename="gz-sim-imu-system"
            name="gz::sim::systems::Imu">
        </plugin>
    </gazebo>

    <gazebo reference="${imu_link}">
      <sensor name="imu_sensor" type="imu">
        <gz_frame_id>imu_link</gz_frame_id>
        <!-- <frame>imu</frame>
        <gz_frame_id>imu</gz_frame_id> -->
        <!-- <pose relative_to='imu'>0 0 0 0 0 0</pose> -->
        <always_on>true</always_on>
        <update_rate>400</update_rate>
        <visualize>true</visualize>
        <topic>/imu/data_raw</topic>
      </sensor>
    </gazebo>
    </xacro:if>

    <!-- IMU joint and link definitions remain the same -->
    <joint name="imu_joint" type="fixed">
      <origin xyz="${imu_origin_xyz}" rpy="${imu_origin_rpy}"/>
      <parent link="${imu_base_link}"/>
      <child link="${imu_link}"/>
    </joint>

    <link name="${imu_link}">
      <inertial>
        <mass value="0.001"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.0001"/>
      </inertial>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="file://$(find smb_description)/urdf/meshes/SMB_imu.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="file://$(find smb_description)/urdf/meshes/SMB_imu.dae"/>
        </geometry>
      </collision>
    </link> 

    <link name="imu_sensor">
      <inertial>
        <mass value="0.001"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.0001"/>
      </inertial>
    </link>

    <joint name="imu_imu_link_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${imu_link}"/>
      <child link="imu_sensor"/>
    </joint>

    <gazebo reference="${imu_link}">
      <material>Gazebo/Orange</material>
    </gazebo>


    <gazebo reference="imu_joint">
      <disableFixedJointLumping>true</disableFixedJointLumping>
    </gazebo>

  </xacro:macro> 
</robot> 
