<?xml version="1.0"?>
<robot name="smb" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:arg name="simulation"   		default="false"/>
  <xacro:arg name="gpu" 		 		default="false"/>
  <xacro:arg name="pointcloud_topic"	default="/rslidar/points"/>

  <xacro:property name="gpu" 		value="$(arg gpu)" />

  <xacro:property name="M_PI" value="3.1415926535897931" />

  <xacro:macro name="LIDAR" params="parent_link simulation">
      
      <!-- Replacing RS-16 with the default Gazebo lidar -->
      <link name="rslidar">
          <inertial>
            <mass value="0.01"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="1e-7" ixy="0" ixz="0" iyy="1e-7" iyz="0" izz="1e-7"/>
          </inertial>
          <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <cylinder radius="0.05" length="0.08"/>
            </geometry>
            <material name="Cyan">
              <color rgba="0 1.0 1.0 1.0"/>
            </material>
          </visual>
      </link>

      <joint name="${parent_link}_to_rslidar" type="fixed">
        <parent link="${parent_link}"/>
        <child link="rslidar"/>
        <origin xyz="0.0 0.0 ${lidarBoxHeight+0.039}" rpy="0 0 0"/>
      </joint>

    <gazebo reference='${parent_link}_to_rslidar'>
      <preserveFixedJoint>true</preserveFixedJoint>
    </gazebo>

      <gazebo>
        <plugin
          filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
          <render_engine>ogre</render_engine>
        </plugin>
      </gazebo>

      <gazebo reference="rslidar">
        <sensor name="rslidar" type="gpu_lidar">
          <gz_frame_id>rslidar</gz_frame_id>
          <pose relative_to='rslidar'>0 0 0 0 0 0</pose>
          <topic>scan</topic>
          <update_rate>10</update_rate>
          <ray>
            <scan>
            <horizontal>
              <samples>360</samples>
              <resolution>1.0</resolution>
              <min_angle>-3.14159</min_angle>
              <max_angle>3.14159</max_angle>
            </horizontal>
            <vertical>
              <samples>16</samples>
              <resolution>1.0</resolution>
              <min_angle>-0.261799</min_angle>
              <max_angle>0.261799</max_angle>
            </vertical>
            </scan>
            
            <!-- Range settings for RS32 -->
            <range>
              <min>0.2</min> 
              <max>50.0</max> 
              <resolution>0.01</resolution>
            </range>
          </ray>
          
          <always_on>1</always_on>
          <visualize>true</visualize>
        </sensor>
      </gazebo>

  </xacro:macro>

</robot>