<?xml version="1.0"?>

<!-- This file contains the Gazebo controller interface. -->
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="robot_gz_diff_drive_plugin">

    <gazebo>
      <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
        <!-- wheels -->
        <left_joint>LF_WHEEL_JOINT</left_joint>
        <left_joint>LH_WHEEL_JOINT</left_joint>

        <right_joint>RF_WHEEL_JOINT</right_joint>
        <right_joint>RH_WHEEL_JOINT</right_joint>

        <!-- kinematics -->
        <wheel_separation>${chassisWidth+wheelClearance*2+wheelWidth}</wheel_separation>
        <wheel_radius>${wheelRadius}</wheel_radius>

        <topic>cmd_vel</topic>

      </plugin>

      <plugin filename="gz-sim-joint-state-publisher-system"
        name="gz::sim::systems::JointStatePublisher">
        <topic>joint_states</topic>
      </plugin>
    </gazebo>

  </xacro:macro>

</robot>