<?xml version="1.0"?>
<robot name="smb" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:arg name="simulation"   		default="false"/>
  <xacro:arg name="gpu" 		 		default="false"/>
  <xacro:arg name="pointcloud_topic"	default="/rslidar/points"/>

  <xacro:property name="gpu" 		value="$(arg gpu)" />

  <xacro:property name="M_PI" value="3.1415926535897931" />

  <xacro:macro name="LIDAR" params="parent_link simulation">

    <xacro:if value="${simulation}">
      
      <!-- Replacing RS-16 with the default Gazebo lidar -->
      <link name="rslidar">
          <inertial>
            <mass value="0.01"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="1e-7" ixy="0" ixz="0" iyy="1e-7" iyz="0" izz="1e-7"/>
          </inertial>
          <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <cylinder radius="0.05" length="0.08"/>
            </geometry>
            <material name="Cyan">
              <color rgba="0 1.0 1.0 1.0"/>
            </material>
          </visual>
      </link>

      <joint name="${parent_link}_to_rslidar" type="fixed">
        <parent link="${parent_link}"/>
        <child link="rslidar"/>
        <origin xyz="0.0 0.0 ${lidarBoxHeight+0.039}" rpy="0 0 0"/>
      </joint>

      <gazebo>
        <plugin
          filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
          <render_engine>ogre2</render_engine>
        </plugin>
      </gazebo>

      <gazebo reference="rslidar">
        <sensor name="rslidar" type="gpu_lidar">
          <frame>rslidar</frame>
          <gz_frame_id>rslidar</gz_frame_id>
          <pose relative_to='rslidar'>0 0 0 0 0 0</pose>
          <topic>scan</topic>
          <update_rate>10</update_rate>
          <ray>
            <scan>
              <!-- Horizontal (360-degree rotation for full field of view) -->
              <horizontal>
                <samples>32</samples> <!-- Higher sample count for denser scan -->
                <resolution>1</resolution>
                <min_angle>-3.14159</min_angle> <!-- -180 degrees -->
                <max_angle>3.14159</max_angle>  <!-- 180 degrees -->
              </horizontal>
              
              <!-- Vertical configuration with 32 channels -->
              <vertical>
                <samples>16</samples> <!-- RS32 has 32 channels -->
                <resolution>1</resolution>
                <min_angle>-0.261799</min_angle> <!-- Approximately -15 degrees in radians -->
                <max_angle>0.261799</max_angle>  <!-- Approximately +15 degrees in radians -->
              </vertical>
            </scan>
            
            <!-- Range settings for RS32 -->
            <range>
              <min>0.2</min> <!-- Minimum detection range -->
              <max>50.0</max> <!-- Maximum detection range; can vary slightly with RS32 models -->
              <resolution>0.01</resolution> <!-- Resolution of 1 cm for high accuracy -->
            </range>
          </ray>
          
          <!-- Visualization for Gazebo UI -->
          <always_on>1</always_on>
          <visualize>true</visualize>
        </sensor>
      </gazebo>


    </xacro:if>

  </xacro:macro>

</robot>