<?xml version="1.0"?>
<robot name="smb" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:arg name="simulation"   		default="false"/>
  <xacro:arg name="gpu" 		 		default="false"/>
  <xacro:arg name="pointcloud_topic"	default="/rslidar/points"/>

  <xacro:property name="gpu" 		value="$(arg gpu)" />

  <xacro:macro name="LIDAR" params="parent_link simulation">

    <xacro:if value="${simulation}">
      
      <!-- Replacing RS-16 with the default Gazebo lidar -->
      <link name="rslidar">
          <inertial>
            <mass value="0.01"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="1e-7" ixy="0" ixz="0" iyy="1e-7" iyz="0" izz="1e-7"/>
          </inertial>
          <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <cylinder radius="0.05" length="0.08"/>
            </geometry>
            <material name="Cyan">
              <color rgba="0 1.0 1.0 1.0"/>
            </material>
          </visual>
      </link>

      <joint name="${parent_link}_to_rslidar" type="fixed">
        <parent link="${parent_link}"/>
        <child link="rslidar"/>
        <origin xyz="0.0 0.0 ${lidarBoxHeight+0.039}" rpy="0 0 0"/>
      </joint>

      <gazebo>
        <plugin
          filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
          <render_engine>ogre2</render_engine>
        </plugin>
      </gazebo>

      <gazebo reference="base_link" >
        <sensor name="base_link" type="gpu_lidar">
          <gz_frame_id>base_link</gz_frame_id>
          <topic>scan</topic>
          <update_rate>30</update_rate>
          <lidar>
            <scan>
              <horizontal>
                <samples>2800</samples>
                <resolution>1</resolution>
                <min_angle>-3.14</min_angle>
                <max_angle>3.14</max_angle>
              </horizontal>
              <vertical>
                <samples>1</samples>
                <resolution>0.1</resolution>
                <min_angle>0.0</min_angle>
                <max_angle>0.0</max_angle>
              </vertical>
            </scan>
            <range>
              <min>0.2</min>
              <max>30.0</max>
              <resolution>0.01</resolution>
            </range>
            <frame_id>/base_link</frame_id>
          </lidar>
          <alwaysOn>ture</alwaysOn>
          <visualize>true</visualize>
        </sensor>
      </gazebo>

    </xacro:if>

  </xacro:macro>

</robot>
